### ISSUE TITLE
The directive has only 10 characters of resolution

### ISSUE THREAD

**Issue by diosney** [jokeyrhyme/element-icon-identicon#1]
I mean, the identicon don't change if the code is greather than 10, so the following identicons has the same picture:

1234567890
1234567890a
1234567890b
1234567890cde

That is too little for my use case since I want to generate an identicon for complex company names that can take at most 20 characters so , there is a way to increase that resolution?

Thanks in advance.

**Comment by diosney** [comment]
I tested again in a clean page and it seems that the resolution is working fine, it seems that some other setting messed up with the code maximum value it could hold (visually it changed correctly that is why the confusion).

Sorry for the misunderstanding and congrats for this useful directive :)

**Comment by jokeyrhyme** [comment]
:D
